# Exercise 4



Below we compute the camera matrix, using the three vanishing points computed in the previous point.

In [11]:
import numpy as np

def compute_K(v1,v2,v3):

    #vanishing points constraints
    a_1=np.array([v2[0]*v1[0],v2[0]*v1[1]+v2[1]*v1[0],v2[1]*v1[1],v2[0]*v1[2]+v2[2]*v1[0],v2[1]*v1[2]+v2[2]*v1[1],v2[2]*v1[2]])
    a_2=np.array([v3[0]*v1[0],v3[0]*v1[1]+v3[1]*v1[0],v3[1]*v1[1],v3[0]*v1[2]+v3[2]*v1[0],v3[1]*v1[2]+v3[2]*v1[1],v3[2]*v1[2]])
    a_3=np.array([v3[0]*v2[0],v3[0]*v2[1]+v3[1]*v2[0],v3[1]*v2[1],v3[0]*v2[2]+v3[2]*v2[0],v3[1]*v2[2]+v3[2]*v2[1],v3[2]*v2[2]])

    #square pixels constraints
    a_4=np.array([0,1,0,0,0,0])
    a_5=np.array([1,0,-1,0,0,0])


    #Stack the vectors vertically to create a 2D array
    A = np.vstack((a_1,a_2,a_3,a_4,a_5))

    _,_,vt = np.linalg.svd(A)
    w_1,w_2,w_3,w_4,w_5,w_6 = vt[-1]

    #w matrix
    W = np.array([[w_1, w_2, w_4], [w_2, w_3, w_5], [w_4, w_5, w_6]])

    #Cholesky Decomposition
    K_inv = np.linalg.cholesky(W)

    #Invert the matrix
    K = np.linalg.inv(K_inv)

    #Normalize K.T by the element at (3,3)

    scaling_factor = K.T[2, 2]  # Element at position (3,3) in K.T
    K_normalized = K.T / scaling_factor

    # Remove elements less than 1e-12
    K_normalized[np.abs(K_normalized) < 1e-12] = 0.0

    # Round to integer
    K_final = K_normalized.astype(int)

    print("Camera matrix")
    print(K_final)

In [12]:
compute_K([1.25584579e+04, 9.85743504e+02, 1.00000000e+00],[ 4.92880107e+02, -1.84714402e+03,  1.00000000e+00],[4.34620226e+02, 1.19562754e+03, 1.00000000e+00])

Camera matrix
[[1068    0  537]
 [   0 1068  755]
 [   0    0    1]]
